services:
  haking-website-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: haking-website-prod
    image: haking-site
    env_file:
      - .env
    environment:
      - PORT=${PORT}
    ports:
      - ${PORT}:${PORT}
  haking-website-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - ${DEV_PORT}:${DEV_PORT}
    develop:
      watch:
        - path: ./src
          target: /app/src
          action: sync
        - path: ./package.json
          target: /app/package.json
          action: restart
        - path: ./vite.config.js
          target: /app/vite.config.js
          action: restart