services:
  haking-website-prod:
    build:
      context: .
      dockerfile: Dockerfile
    image: haking-site
    ports:
      - "8080:8080"
  haking-website-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    develop:
      watch:
        - path: ./src
          target: /app/src
          action: sync
        - path: ./package.json
          target: /app/package.json
          action: restart
        - path: ./vite.config.js
          target: /app/vite.config.js
          action: restart